version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.CrmSdk.XrmTooling.CoreAssembly
    versions:
    - 9.1.0.68
    - 9.1.0.77
  - dependency-name: Microsoft.CrmSdk.Workflow
    versions:
    - 9.0.2.29
    - 9.0.2.32
  - dependency-name: Microsoft.CrmSdk.Deployment
    versions:
    - 9.0.2.29
    - 9.0.2.32
  - dependency-name: Microsoft.CrmSdk.CoreAssemblies
    versions:
    - 9.0.2.29
    - 9.0.2.32
  - dependency-name: MscrmTools.Xrm.Connection
    versions:
    - 1.2021.1.39
  - dependency-name: XrmToolBoxPackage
    versions:
    - 1.2020.12.43
  - dependency-name: Microsoft.IdentityModel.Clients.ActiveDirectory
    versions:
    - 5.2.8
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
